[versions]
agp = "8.3.0"
kotlin = "1.9.22"
ndk = "28.2.13676358"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
